@startuml
left to right direction
actor "Usuário" as Usuario

rectangle Funcionarios {
  Usuario -> (Cadastrar Funcionario)
  Usuario -> (Alterar Funcionario)
  Usuario -> (Consultar Funcionario)
  Usuario -> (Excluir Funcionario)
}
@enduml